- name: set computer's hostname
  command: "hostnamectl set-hostname {{hostname}}"

- name: ensure system is updated
  dnf:
    name: "*"
    state: latest


- name: set default keyboard layout
  command: localectl set-keymap us-intl
  
- name: set x11 key map
  command: localectl set-x11-keymap us,us intl

- name: ensure base packages are installed
  dnf: 
    name:
      # tools
      - htop
      - git
      - tig
      - lshw
      - tmux
      - vim
      - keepassx
      - fzf
      - ripgrep
      - fd-find
      - the_silver_searcher
      - ranger
      - gimp
      # system packages
      - openssl-devel
      - tk-devel
      - java-latest-openjdk.x86_64

- name: install c related dev tools
  yum:
    name:
      - groupinstall 'Development Tools'
    state: latest

- name: ensure base python packages are installed
  dnf:
    name:
      - python-pip
      - python-psutil
      - python-devel
      - python3-tkinter

- name: ensure base ruby packages are installed
  dnf:
    name:
      ruby
