- name: set computer's hostname
  command: "hostnamectl set-hostname {{hostname}}"

- name: ensure system is updated
  dnf:
    name: "*"
    state: latest


- name: set default keyboard layout
  command: localectl set-keymap us-intl
  
- name: set x11 key map
  command: localectl set-x11-keymap us,us intl

- name: ensure base packages are installed
  dnf: 
    name:
      # tools
      - htop
      - git
      - tig
      - lshw
      - tmux
      - vim
      - keepassx
      - fzf
      - ripgrep
      - fd-find
      - the_silver_searcher
      - ranger
      - gimp
      - gnome-shell-extension-pomodoro
      # system packages
      - openssl-devel
      - tk-devel
      - java-latest-openjdk.x86_64
      - java-devel
      - ffmpeg
      - ffmpeg-devel
      # docker dependencies
      - dnf-plugins-core

- name: install c related dev tools
  yum:
    name:
      - groupinstall 'Development Tools'
    state: latest

- name: ensure docker is installed
  become: true
  block:
    - name: Install the docker comunity edition package
      dnf:
        name:
          - moby-engine
    - name: Backwards compatibility with cgroups for Fedora >= 31 
      shell: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
    - name: Start docker service
      systemd:
        state: started
        name: docker
    - name: Create docker group
      shell: newgrp docker
    - name: Add username to the docker group
      shell: "usermod -a -G docker {{username}}" # The system should be restarted 

  tags:
    - packages

- name: ensure base python packages are installed
  dnf:
    name:
      - python-pip
      - python-psutil
      - python-devel
      - python3-tkinter

- name: ensure base ruby packages are installed
  dnf:
    name:
      ruby
