- name: set computer's hostname
  command: "hostnamectl set-hostname {{hostname}}"

- name: ensure system is updated
  dnf:
    name: "*"
    state: latest

- name: ensure base packages are installed
  dnf: 
    name:
      - htop
      - git
      - tig
      - lshw
      - tmux
      - vim
    state: latest

- name: ensure base python packages are installed
  dnf:
    name:
      - python-pip
      - python-psutil

- name: ensure base ruby packages are installed
  dnf:
    name:
      ruby
