- name: set computer's hostname
  command: "hostnamectl set-hostname {{hostname}}"

- name: ensure system is updated
  dnf:
    name: "*"
    state: latest


- name: set default keyboard layout
  command: localectl set-keymap us-intl
  
- name: set x11 key map
  command: localectl set-x11-keymap us,us intl

- name: ensure base packages are installed
  dnf: 
    name:
      - htop
      - git
      - tig
      - lshw
      - tmux
      - vim
      - keepassx
      - fzf
      - ripgrep
      - fd-find
      - the_silver_searcher
      - ranger

    state: latest

- name: ensure base python packages are installed
  dnf:
    name:
      - python-pip
      - python-psutil
      - python-devel

- name: ensure base ruby packages are installed
  dnf:
    name:
      ruby
