- name: ensure nvim is installed
  become: true
  dnf:
    name:
      - neovim
      - python3-neovim

- name: ensure the nvim conf repo is cloned
  git:
    repo: https://github.com/IsmaelMT/nvim-conf.git
    dest: $HOME/nvim-conf

- name: ensure the nvim repo is installed
  command: chdir=$HOME/nvim-conf sh install.sh
