- name: ensure the gnome packages are installed
  become: true
  dnf:
    name:
      - gnome-tweaks
      - arc-theme
      - la-capitaine-icon-theme

- name: set wallpaper
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///{{ ansible_env.HOME }}/provisioning/fedora/wallpaper/zelda.jpg'"

- name: set gnome gtk theme
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc-Dark'"

- name: set gnome icon theme
  dconf: key="/org/gnome/desktop/interface/icon-theme" value="'La-Capitaine'"

- name: set gnome window theme
  dconf: key="/org/gnome/desktop/wm/preferences/theme" value="'Wayland'"

- name: set gnome battery percentage
  dconf: key="/org/gnome/desktop/interface/show-battery-percentage" value="'true'"
