- hosts: all
  connection: local
  user: ismaelmt
  roles:
    # - {role: common, become: true}
    - {role: nvidia, become: true}
    # - {role: langs, become: false}
    # - {role: devtools, become: false, username: ismaelmt}
