- name: ensure nvm is installed
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    executable: /bin/zsh
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  notify:
    - source zshrc

- name: ensure latest node version is installed
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
  args:
    executable: /bin/zsh

- name: ensure yarn repo is addded
  become: true
  yum_repository:
    name: yarn
    description: Yarn repository
    baseurl: "https://dl.yarnpkg.com/rpm"
    gpgcheck: yes
    enabled: 1
    gpgkey: "https://dl.yarnpkg.com/rpm/pubkey.gpg"

- name: ensure yarn is installed
  become: true
  dnf:
    name:
      - yarn
