- name: ensure poetry is installed and configured
  block:
    - name: Install poetry
      shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Create poetry completions directory if it does not exist
      file:
        path: $HOME/.oh-my-zsh/plugins/poetry
        state: directory
    - name: install poetry completions for zsh
      shell: poetry completions zsh > $HOME/.oh-my-zsh/plugins/poetry/_poetry

- name: ensure python base user packages are installed
  become: true
  pip:
    name: ranger-fm

- name: ensure python base user packages are installed
  pip:
    name: pipx
    extra_args: --user

- name: add pipx binary directories to PATH
  command: $HOME/.local/bin/pipx ensurepath
# TODO: add this kind of scripts in templates?
# - name: add pipx completions
#   shell: autoload -U bashcompinit && bashcompinit && eval "$(register-python-argcomplete pipx)"
#   args:
#     executable: /bin/zsh
